import {onAuthStateChanged,dbGet,dbSet,dbPush} from "./firebase.js";
import {EXAMS,DEMO_TESTS,COURSES,PAYMENT} from "./data.js";
import {header,footer,esc,trackActivity,logout} from "./ui.js";
header();footer();
const $=id=>document.getElementById(id);
const examName=id=>EXAMS.find(e=>e.id===id)?.name||"All Exams";
const courseById=id=>COURSES.find(c=>c.id===id);
const money=n=>Number(n||0)===0?"Free":"₹"+Number(n||0).toLocaleString("en-IN");
const date=v=>v?new Date(v).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
async function userState(){return new Promise(resolve=>{let done=false;onAuthStateChanged(u=>{if(!done){done=true;resolve(u);}});});}

function examCards(target){if(!target)return;target.innerHTML=EXAMS.map(e=>`<article class="exam-card card"><div class="exam-icon">${esc(e.icon)}</div><span class="pill">${esc(e.tag)}</span><h3>${esc(e.name)}</h3><p>${esc(e.desc)}</p><a class="text-link" href="exam-details.html?exam=${encodeURIComponent(e.id)}">Explore ${esc(e.name)} →</a></article>`).join("");}
examCards($("exam-grid"));

async function renderCourses(target){
 if(!target)return;
 let list=COURSES;
 try{const s=await dbGet("courses");if(s.exists())list=Object.entries(s.val()).map(([id,v])=>({...v,id}));}catch{}
 target.innerHTML=list.map(c=>`<article class="card course-card ${c.type}">
   <div class="course-head"><div class="course-icon">${esc(c.icon||"◈")}</div><span class="pill ${c.type}">${c.type==="free"?"FREE":"PAID"}</span></div>
   <div class="course-label">${c.type==="free"?"LIMITED FOUNDATION":"COMPLETE PREMIUM COURSE"}</div>
   <h3>${esc(c.title)}</h3><p>${esc(c.desc)}</p>
   <ul class="mini-list">${(c.highlights||[]).slice(0,5).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>
   <div class="course-meta"><strong>${money(c.price)}</strong><span>${esc(examName(c.examId))}</span></div>
   <a class="btn small" href="course.html?id=${encodeURIComponent(c.id)}">${c.type==="free"?"View Free Course":"View Premium Course"}</a>
 </article>`).join("");
}
renderCourses($("course-grid"));

async function renderTests(){const el=$("tests-grid");if(!el)return;let tests=[...DEMO_TESTS];try{const s=await dbGet("tests");if(s.exists())tests=Object.entries(s.val()).map(([id,v])=>({...v,id})).concat(DEMO_TESTS);}catch{}el.innerHTML=tests.map(t=>`<article class="card test-card"><div class="test-top"><span class="pill">${esc(examName(t.examId))}</span><span class="test-time">${t.duration||0} min</span></div><h3>${esc(t.title)}</h3><p>${t.questions?.length||0} questions · ${t.free===false?"Premium":"Free practice"}</p><a class="btn small" href="test.html?test=${encodeURIComponent(t.id)}">Start Test</a></article>`).join("")||`<div class="empty">No tests available yet.</div>`;}
renderTests();

const examId=new URLSearchParams(location.search).get("exam");
if($("exam-details")){const e=EXAMS.find(x=>x.id===examId);$("exam-details").innerHTML=e?`<div class="detail-hero"><div class="exam-icon large">${esc(e.icon)}</div><div><span class="pill">${esc(e.tag)}</span><h1>${esc(e.name)}</h1><p>${esc(e.desc)}</p></div></div><div class="feature-grid"><div class="feature"><b>Free foundation</b><span>Limited selected topics after account registration.</span></div><div class="feature"><b>Premium preparation</b><span>Unlimited topic coverage, premium tests and additional resources.</span></div><div class="feature"><b>Recruitment updates</b><span>Recent government vacancy information for aspirants.</span></div></div><div class="detail-actions"><a class="btn" href="courses.html">View Courses</a><a class="btn ghost" href="mock-tests.html">View Mock Tests</a></div>`:`<div class="empty">Exam not found.</div>`;}

async function runTest(){const root=$("test-root");if(!root)return;const id=new URLSearchParams(location.search).get("test");let test=DEMO_TESTS.find(t=>t.id===id);try{const s=await dbGet("tests/"+id);if(s.exists())test={...s.val(),id};}catch{}if(!test){root.innerHTML=`<div class="empty">Test not found.</div>`;return;}const user=await userState();if(!user){root.innerHTML=`<div class="login-required"><span class="eyebrow">ASPIRANT ACCESS</span><h1>Account required</h1><p>Create a free aspirant account or login before attempting a test so your score can be saved.</p><a class="btn" href="login.html?next=${encodeURIComponent(location.href)}">Login</a><a class="btn ghost" href="register.html">Create Account</a></div>`;return;}root.className="test-shell";root.innerHTML=`<div class="test-heading"><div><span class="pill">${esc(examName(test.examId))}</span><h1>${esc(test.title)}</h1><p>${test.questions.length} questions · ${test.duration} minutes</p></div><div class="timer" id="timer">${test.duration}:00</div></div><form id="test-form">${test.questions.map((q,i)=>`<fieldset class="question"><legend><span>${i+1}</span>${esc(q.text)}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${esc(o)}</span></label>`).join("")}</fieldset>`).join("")}<button class="btn" type="submit">Submit Test</button><p id="test-msg" class="message"></p></form>`;let seconds=(test.duration||20)*60,submitted=false;const timer=$("timer"),form=$("test-form");const tick=()=>{timer.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;if(seconds<=0&&!submitted){submitted=true;form.requestSubmit();}else seconds--;};tick();const interval=setInterval(tick,1000);form.addEventListener("submit",async ev=>{ev.preventDefault();clearInterval(interval);if(form.dataset.saved)return;form.dataset.saved="1";const data=new FormData(form);let score=0;const answers={};test.questions.forEach((q,i)=>{const a=Number(data.get("q"+i));answers[q.id]=a;if(a===q.answer)score++;});const btn=form.querySelector("button");btn.disabled=true;btn.textContent="Saving result…";try{const ref=await dbPush(`users/${user.uid}/results`);const result={testId:test.id,testTitle:test.title,examId:test.examId,userId:user.uid,score,total:test.questions.length,percentage:Math.round(score/test.questions.length*100),answers,submittedAt:Date.now()};await dbSet(`users/${user.uid}/results/${ref.key}`,result);await dbSet(`results/${ref.key}`,result);await trackActivity(user,"test_submission",{testId:test.id,testTitle:test.title,score,total:test.questions.length});location.href="result.html?id="+encodeURIComponent(ref.key);}catch(error){$("test-msg").textContent=error.message;form.dataset.saved="";btn.disabled=false;btn.textContent="Submit Test";}});}
runTest();

async function renderResult(){const root=$("result-root");if(!root)return;const id=new URLSearchParams(location.search).get("id");const user=await userState();if(!user){location.href="login.html";return;}try{let s=await dbGet(`users/${user.uid}/results/${id}`);if(!s.exists())s=await dbGet(`results/${id}`);if(!s.exists()||s.val().userId!==user.uid){root.innerHTML=`<div class="empty">Result not found.</div>`;return;}const r=s.val();root.innerHTML=`<div class="result-card"><span class="eyebrow">TEST COMPLETED</span><h1>${esc(r.testTitle)}</h1><div class="score-ring"><strong>${r.percentage}%</strong><span>${r.score} / ${r.total}</span></div><p>Your result is saved in your private aspirant record.</p><div class="detail-actions"><a class="btn" href="mock-tests.html">More Tests</a><a class="btn ghost" href="dashboard.html">My Dashboard</a></div></div>`;}catch(error){root.innerHTML=`<div class="empty">${esc(error.message)}</div>`;}}
renderResult();

async function renderDashboard(){const name=$("student-name");if(!name)return;const user=await userState();if(!user){location.href="login.html";return;}let profile={name:user.displayName||user.email.split("@")[0],email:user.email,targetExam:""};try{const s=await dbGet(`users/${user.uid}`);if(s.exists())profile={...profile,...s.val()};}catch{}name.textContent=profile.name;const emailEl=$("student-email");if(emailEl)emailEl.textContent=profile.email;const targetEl=$("student-target");if(targetEl)targetEl.textContent=profile.targetExam?examName(profile.targetExam):"Not selected";let purchases=[];try{const s=await dbGet(`users/${user.uid}/purchases`);if(s.exists())purchases=Object.values(s.val()).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));}catch{}const pc=$("purchase-list");if(pc)pc.innerHTML=purchases.map(p=>`<div class="result-row"><div><b>${esc(p.courseTitle)}</b><small>${esc(p.status||"pending")} · ${date(p.createdAt)}</small></div><strong>${money(p.amount)}</strong></div>`).join("")||`<div class="empty">No premium course purchases yet.</div>`;let results=[];try{const s=await dbGet(`users/${user.uid}/results`);if(s.exists())results=Object.values(s.val()).sort((a,b)=>(b.submittedAt||0)-(a.submittedAt||0));}catch{}const rl=$("results-list");if(rl)rl.innerHTML=results.slice(0,10).map(r=>`<div class="result-row"><div><b>${esc(r.testTitle)}</b><small>${date(r.submittedAt)}</small></div><strong>${r.percentage}%</strong></div>`).join("")||`<div class="empty">No tests attempted yet.</div>`;}
renderDashboard();
$("dashboard-logout")?.addEventListener("click",async()=>{await logout();});

async function renderCourse(){
 const root=$("course-root");if(!root)return;
 const id=new URLSearchParams(location.search).get("id");const course=courseById(id);
 if(!course){root.innerHTML=`<div class="empty">Course not found.</div>`;return;}
 const user=await userState();
 if(!user){root.innerHTML=`<div class="course-hero-card"><span class="pill ${course.type}">${course.type==="free"?"FREE COURSE":"PAID COURSE"}</span><h1>${esc(course.title)}</h1><p>${esc(course.desc)}</p><div class="price-xl">${money(course.price)}</div><div class="notice"><b>Registration is mandatory.</b><br>Create an aspirant account or login to access this course.</div><div class="detail-actions"><a class="btn" href="register.html?next=${encodeURIComponent(location.href)}">Create Account</a><a class="btn ghost" href="login.html?next=${encodeURIComponent(location.href)}">Login</a></div></div>`;return;}
 let access=false,purchase=null,enrolled=false;
 if(course.type==="free"){
   try{const a=await dbGet(`users/${user.uid}/enrollments/${course.id}`);enrolled=a.exists()&&a.val()===true;access=enrolled;}catch{}
 }else{
   try{const s=await dbGet(`users/${user.uid}/purchases`);if(s.exists())purchase=Object.values(s.val()).find(p=>p.courseId===course.id&&(p.status==="approved"||p.status==="pending"));}catch{}
   try{const a=await dbGet(`courseAccess/${user.uid}/${course.id}`);access=a.exists()&&a.val()===true;}catch{}
 }
 if(!access){
   const action=course.type==="free"?`<button class="btn" id="enroll-free">Enroll in Free Course</button>`:(purchase?`<div class="notice"><b>Purchase status:</b> ${esc(purchase.status)}${purchase.transactionId?` · Transaction: ${esc(purchase.transactionId)}`:""}</div><p class="muted">Access will appear automatically after your payment is verified.</p>`:`<a class="btn" href="purchase.html?course=${encodeURIComponent(course.id)}">Buy this Premium Course · ${money(course.price)}</a>`);
   root.innerHTML=`<div class="course-hero-card"><div class="course-icon large">${esc(course.icon||"◈")}</div><span class="pill ${course.type}">${course.type==="free"?"FREE · LIMITED":"PAID · PREMIUM"}</span><h1>${esc(course.title)}</h1><p>${esc(course.desc)}</p><ul class="course-feature-list">${(course.highlights||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul><div class="price-xl">${money(course.price)}</div>${action}<p id="course-msg" class="message"></p></div>`;
   if(course.type==="free")$("enroll-free")?.addEventListener("click",async e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="Enrolling…";try{await dbSet(`users/${user.uid}/enrollments/${course.id}`,true);await dbSet(`users/${user.uid}/enrollmentMeta/${course.id}`,{courseId:course.id,courseTitle:course.title,type:"free",enrolledAt:Date.now()});await trackActivity(user,"free_course_enrollment",{courseId:course.id,courseTitle:course.title});await renderCourse();}catch(err){$("course-msg").textContent=err.message;e.currentTarget.disabled=false;e.currentTarget.textContent="Enroll in Free Course";}});
   return;
 }
 let content=`<div class="course-hero-card"><span class="pill ${course.type}">${course.type==="free"?"FREE COURSE — ENROLLED":"PREMIUM ACCESS ACTIVE"}</span><h1>${esc(course.title)}</h1><p>${esc(course.desc)}</p><ul class="course-feature-list">${(course.highlights||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`;
 try{const s=await dbGet(`courseContent/${course.id}`);if(s.exists()){const lessons=Object.values(s.val());content+=`<div class="lesson-list">${lessons.map((l,i)=>`<article class="card"><span class="pill">LESSON ${i+1}</span><h3>${esc(l.title||"Lesson")}</h3><p>${esc(l.body||"")}</p></article>`).join("")}</div>`;}else content+=`<div class="card empty">Your access is active. Course lessons/resources will appear here when published.</div>`;}catch{content+=`<div class="card empty">Could not load course content.</div>`;}root.innerHTML=content;
}
renderCourse();

async function renderPurchase(){
 const root=$("purchase-root");if(!root)return;const id=new URLSearchParams(location.search).get("course");const course=courseById(id);
 if(!course||course.type!=="paid"){root.innerHTML=`<div class="empty">Premium course not found.</div>`;return;}
 const user=await userState();if(!user){root.innerHTML=`<div class="login-required"><span class="eyebrow">PREMIUM PURCHASE</span><h1>Account required</h1><p>You must create an aspirant account or login before purchasing a premium course.</p><div class="detail-actions"><a class="btn" href="register.html?next=${encodeURIComponent(location.href)}">Create Account</a><a class="btn ghost" href="login.html?next=${encodeURIComponent(location.href)}">Login</a></div></div>`;return;}
 const upiLink=`upi://pay?pa=${encodeURIComponent(PAYMENT.upiId)}&pn=${encodeURIComponent(PAYMENT.payeeName||"Asha Sorkari Sakori")}&am=${encodeURIComponent(course.price)}&cu=INR&tn=${encodeURIComponent(course.title)}`;
 root.innerHTML=`<div class="purchase-card card"><div class="purchase-top"><div><span class="pill paid">PREMIUM COURSE</span><h1>${esc(course.title)}</h1><p>${esc(course.desc)}</p></div><div class="purchase-price"><small>Course fee</small><strong>${money(course.price)}</strong></div></div><div class="payment-layout"><div class="payment-box qr-panel"><span class="eyebrow">STEP 1 · PAY</span><h3>Scan the secure payment QR</h3><p>Scan this QR with any UPI app. The payment details and exact course amount are embedded in the QR.</p><div id="payment-qr" class="payment-qr" aria-label="Dynamic UPI payment QR"></div><a class="btn small" href="${upiLink}">Open UPI payment app</a><p class="privacy-note">The payment address is intentionally not displayed on this page.</p></div><div class="payment-box"><span class="eyebrow">STEP 2 · VERIFY</span><h3>Submit your UTR / transaction reference</h3><p>After payment, return here and paste the UTR/reference number from your UPI app. Your request stays <b>Pending</b> until the owner verifies it.</p><form id="purchase-form"><label>UTR / Transaction Reference ID<input id="transaction-id" required maxlength="80" autocomplete="off" placeholder="Paste your UTR / reference number"></label><label>Payment date<input id="payment-date" type="date" required></label><button class="btn" type="submit">Submit Payment for Verification</button><p id="purchase-msg" class="message"></p></form></div></div><div class="notice"><b>Important:</b> Do not submit a UTR unless payment has actually been completed. Premium access is activated only after manual verification.</div></div>`;
 if(window.QRCode){new QRCode($("payment-qr"),{text:upiLink,width:230,height:230,correctLevel:QRCode.CorrectLevel.M});}else{$("payment-qr").innerHTML=`<p class="message error">Payment QR could not load. Please refresh the page.</p>`;}
 const dateInput=$("payment-date");if(dateInput)dateInput.value=new Date().toISOString().slice(0,10);
 const form=$("purchase-form");form.addEventListener("submit",async e=>{e.preventDefault();const tid=$("transaction-id").value.trim(),paymentDate=$("payment-date").value;if(!tid||!paymentDate)return;const btn=form.querySelector("button");btn.disabled=true;btn.textContent="Submitting…";try{const ref=await dbPush("purchases");const purchase={purchaseId:ref.key,userId:user.uid,userName:user.displayName||"",userEmail:user.email,courseId:course.id,courseTitle:course.title,amount:course.price,transactionId:tid,paymentDate,status:"pending",createdAt:Date.now()};await dbSet(`purchases/${ref.key}`,purchase);await dbSet(`users/${user.uid}/purchases/${ref.key}`,purchase);await trackActivity(user,"payment_verification_submitted",{purchaseId:ref.key,courseId:course.id,courseTitle:course.title,amount:course.price});$("purchase-msg").className="message success";$("purchase-msg").textContent="Payment submitted for verification. Track the status from your dashboard.";btn.textContent="Submitted";}catch(error){$("purchase-msg").className="message error";$("purchase-msg").textContent=error.message;btn.disabled=false;btn.textContent="Submit Payment for Verification";}});
}
renderPurchase();

if($("affairs-list")){
 const el=$("affairs-list");(async()=>{let items=[];try{const s=await dbGet("currentAffairs");if(s.exists())items=Object.values(s.val()).sort((a,b)=>(b.date||0)-(a.date||0));}catch{}el.innerHTML=items.slice(0,30).map(x=>`<article class="card"><span class="pill">${esc(x.category||"CURRENT AFFAIRS")}</span><h3>${esc(x.title||"Update")}</h3><p>${esc(x.summary||x.description||"")}</p><small>${date(x.date)}</small></article>`).join("")||`<article class="card"><span class="pill">ASSAM + INDIA</span><h3>Exam-oriented Current Affairs</h3><p>Important appointments, schemes, awards, sports, national events and Assam-specific developments will be published here.</p></article>`;})();
}
if($("study-list"))$("study-list").innerHTML=EXAMS.map(e=>`<article class="card"><div class="exam-icon">${esc(e.icon)}</div><span class="pill">${esc(e.tag)}</span><h3>${esc(e.name)} Resources</h3><p>${esc(e.desc)}</p><a class="btn small" href="exam-details.html?exam=${encodeURIComponent(e.id)}">Open Resources</a></article>`).join("");

async function renderJobs(){const el=$("jobs-list");if(!el)return;let jobs=[];try{const s=await dbGet("jobs");if(s.exists())jobs=Object.entries(s.val()).map(([id,v])=>({...v,id}));}catch{}jobs.sort((a,b)=>(b.publishedAt||b.createdAt||0)-(a.publishedAt||a.createdAt||0));el.innerHTML=jobs.map(j=>`<article class="card job-card"><div class="job-top"><span class="pill">${esc(j.status||"OPEN")}</span>${j.lastDate?`<span class="deadline">Last date: ${date(j.lastDate)}</span>`:""}</div><h3>${esc(j.title||"")}</h3><p><b>${esc(j.organization||"")}</b></p><p>${esc(j.description||"")}</p><div class="job-meta">${j.postCount?`<span>${esc(String(j.postCount))} posts</span>`:""}${j.publishedAt?`<span>Published ${date(j.publishedAt)}</span>`:""}</div><a class="btn small" href="job-details.html?id=${encodeURIComponent(j.id)}">View Vacancy</a></article>`).join("")||`<div class="empty">No recent government vacancies have been published yet. Check back for new recruitment updates.</div>`;}
renderJobs();
async function renderJobDetails(){const el=$("job-details");if(!el)return;const id=new URLSearchParams(location.search).get("id");try{const s=await dbGet("jobs/"+id);if(s.exists()){const j=s.val();el.innerHTML=`<span class="pill">${esc(j.status||"RECRUITMENT")}</span><h1>${esc(j.title)}</h1><p class="lead"><b>${esc(j.organization||"")}</b></p><div class="job-facts">${j.postCount?`<div><small>Posts</small><b>${esc(String(j.postCount))}</b></div>`:""}${j.lastDate?`<div><small>Last date</small><b>${date(j.lastDate)}</b></div>`:""}${j.publishedAt?`<div><small>Published</small><b>${date(j.publishedAt)}</b></div>`:""}</div><div class="job-detail-text">${esc(j.description||"No description available.")}</div>${j.applyUrl?`<a class="btn" target="_blank" rel="noopener" href="${esc(j.applyUrl)}">Official Apply Link ↗</a>`:""}`;return;}}catch{}el.innerHTML=`<div class="empty">Vacancy not found.</div>`;}
renderJobDetails();
