import {onAuthStateChanged,dbGet,dbSet,dbUpdate,dbPush} from '../js/firebase.js';
import {EXAMS,COURSES} from '../js/data.js';
import {header,footer,esc,formatMoney,formatDate} from '../js/ui.js';
header();footer();
const $=id=>document.getElementById(id);
const examName=id=>EXAMS.find(e=>e.id===id)?.name||'Not selected';
async function read(path){try{const s=await dbGet(path);return s.exists()?s.val():{};}catch{return {};}}
async function requireAdmin(){return new Promise(resolve=>{let settled=false;onAuthStateChanged(async user=>{if(settled)return;settled=true;if(!user){location.href='../login.html?next='+encodeURIComponent(location.href);return;}const ok=await dbGet(`admins/${user.uid}`).catch(()=>null);if(!ok?.exists()||ok.val()!==true){document.querySelector('main').innerHTML=`<section class="section container narrow"><div class="access-card"><div class="access-icon">⛔</div><span class="eyebrow">PRIVATE OWNER AREA</span><h2>Admin access required</h2><p>This area is restricted to the owner/admin account configured in the Asha Sorkari Sakori Firebase database.</p><a class="btn" href="../dashboard.html">Back to Dashboard</a></div></section>`;return;}resolve(user);});});}
const admin=await requireAdmin();if(!admin)throw new Error('Admin access denied');

async function renderBureau(){
 const root=$('admin-root');if(!root)return;
 const [users,purchases,results,activity,jobs]=await Promise.all([read('users'),read('purchases'),read('results'),read('activity'),read('jobs')]);
 const U=Object.values(users||{}),P=Object.values(purchases||{}),R=Object.values(results||{}),J=Object.values(jobs||{});
 const A=Object.values(activity||{}).flatMap(x=>Object.values(x||{})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));
 const pending=P.filter(x=>x.status==='pending'),approved=P.filter(x=>x.status==='approved'),revenue=approved.reduce((n,x)=>n+Number(x.amount||0),0);
 const targets={};U.forEach(u=>targets[u.targetExam||'Not selected']=(targets[u.targetExam||'Not selected']||0)+1);
 const courses={};P.forEach(p=>courses[p.courseTitle||p.courseId]=(courses[p.courseTitle||p.courseId]||0)+1);
 root.innerHTML=`<div class="admin-top"><div><span class="eyebrow">OWNER CONSOLE</span><h2>Aspirant Data Bureau</h2><p>Private operational view of the competitive-exam platform.</p></div><div class="admin-user">Owner session<br><b>${esc(admin.email||'Authenticated')}</b></div></div>
 <div class="admin-stats"><div><span>Total aspirants</span><strong>${U.length}</strong></div><div><span>Premium requests</span><strong>${P.length}</strong></div><div><span>Pending verification</span><strong>${pending.length}</strong></div><div><span>Approved revenue</span><strong>${formatMoney(revenue)}</strong></div><div><span>Tests submitted</span><strong>${R.length}</strong></div><div><span>Published jobs</span><strong>${J.length}</strong></div></div>
 <div class="admin-panels"><section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">PURCHASE BUREAU</span><h3>Payment verification</h3></div><span class="admin-count">${pending.length} pending</span></div><div class="admin-table"><table><thead><tr><th>Aspirant</th><th>Course</th><th>Amount</th><th>UTR</th><th>Status</th><th></th></tr></thead><tbody>${P.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(p=>`<tr><td><b>${esc(p.userName||'Aspirant')}</b><small>${esc(p.userEmail||'')}</small></td><td>${esc(p.courseTitle||p.courseId||'')}</td><td>${formatMoney(p.amount)}</td><td>${esc(p.transactionId||'—')}</td><td><span class="status-chip ${esc(p.status||'pending')}">${esc(p.status||'pending')}</span></td><td>${p.status==='approved'?`<button class="btn tiny danger" data-revoke="${esc(p.purchaseId)}" data-user="${esc(p.userId)}" data-course="${esc(p.courseId)}">Revoke</button>`:`<button class="btn tiny" data-approve="${esc(p.purchaseId)}" data-user="${esc(p.userId)}" data-course="${esc(p.courseId)}">Approve</button>`}</td></tr>`).join('')||'<tr><td colspan="6">No purchase requests yet.</td></tr>'}</tbody></table></div></section>
 <section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">AUDIENCE</span><h3>Exam interest</h3></div></div><div class="admin-bars">${Object.entries(targets).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div><div><b>${esc(examName(k))}</b><span>${v}</span></div><i style="width:${Math.max(5,Math.min(100,(v/Math.max(1,U.length))*100))}%"></i></div>`).join('')||'<p class="muted">No aspirants registered yet.</p>'}</div></section></div>
 <section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">ASPIRANT DATABASE</span><h3>Who is preparing for what?</h3></div><a class="text-link" href="users.html">Open full database →</a></div><div class="admin-table"><table><thead><tr><th>Aspirant</th><th>Target exam</th><th>Free</th><th>Premium</th><th>Registered</th><th>Last login</th></tr></thead><tbody>${U.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,30).map(u=>{const ps=P.filter(p=>p.userId===u.uid);return `<tr><td><b>${esc(u.name||'—')}</b><small>${esc(u.email||'')}</small></td><td>${esc(examName(u.targetExam))}</td><td>${Object.keys(u.enrollments||{}).length}</td><td>${ps.length}</td><td>${formatDate(u.createdAt)}</td><td>${formatDate(u.lastLogin)}</td></tr>`}).join('')||'<tr><td colspan="6">No aspirants yet.</td></tr>'}</tbody></table></div></section>
 <section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">ACTIVITY LOG</span><h3>Recent platform activity</h3><p>Registration, login, logout, enrolment, payment verification and test submission.</p></div></div><div class="admin-table"><table><thead><tr><th>Time</th><th>Email</th><th>Activity</th><th>Details</th></tr></thead><tbody>${A.slice(0,100).map(a=>`<tr><td>${formatDate(a.createdAt)}<small>${a.createdAt?new Date(a.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):''}</small></td><td>${esc(a.email||'—')}</td><td><span class="status-chip">${esc(a.action||'activity')}</span></td><td><small>${esc(JSON.stringify(a.details||{}))}</small></td></tr>`).join('')||'<tr><td colspan="4">No activity recorded yet.</td></tr>'}</tbody></table></div></section>
 <section class="admin-panel"><div class="admin-panel-head"><div><span class="eyebrow">CONTENT</span><h3>Quick publishing</h3><p>Publish a government vacancy directly from the owner console.</p></div></div><form id="job-form" class="admin-form"><div><label>Job / post title<input id="job-title" required placeholder="e.g. Assam Government Recruitment 2026"></label><label>Organization<input id="job-org" required placeholder="Department / Commission"></label></div><div><label>Number of posts<input id="job-posts" placeholder="e.g. 120"></label><label>Last date<input id="job-last" type="date"></label></div><label>Description<textarea id="job-desc" rows="4" placeholder="Eligibility, important details and notification summary"></textarea></label><label>Official application URL<input id="job-url" type="url" placeholder="https://official-website..."></label><button class="btn" type="submit">Publish Vacancy</button><p id="job-msg" class="form-message"></p></form></section>`;
 root.querySelectorAll('[data-approve]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{const id=btn.dataset.approve,uid=btn.dataset.user,cid=btn.dataset.course;await dbUpdate('',{[`purchases/${id}/status`]:'approved',[`users/${uid}/purchases/${id}/status`]:'approved',[`courseAccess/${uid}/${cid}`]:true});await renderBureau();}catch(e){btn.disabled=false;alert(e.message);}});
 root.querySelectorAll('[data-revoke]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{const id=btn.dataset.revoke,uid=btn.dataset.user,cid=btn.dataset.course;await dbUpdate('',{[`purchases/${id}/status`]:'revoked',[`users/${uid}/purchases/${id}/status`]:'revoked',[`courseAccess/${uid}/${cid}`]:false});await renderBureau();}catch(e){btn.disabled=false;alert(e.message);}});
 $('job-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button'),msg=$('job-msg');b.disabled=true;b.textContent='Publishing…';try{const ref=await dbPush('jobs');const job={title:$('job-title').value.trim(),organization:$('job-org').value.trim(),postCount:$('job-posts').value.trim(),lastDate:$('job-last').value||'',description:$('job-desc').value.trim(),applyUrl:$('job-url').value.trim(),status:'OPEN',publishedAt:Date.now(),createdAt:Date.now()};await dbSet(`jobs/${ref.key}`,job);msg.className='form-message success';msg.textContent='Vacancy published.';e.currentTarget.reset();b.disabled=false;b.textContent='Publish Vacancy';await renderBureau();}catch(err){msg.className='form-message error';msg.textContent=err.message;b.disabled=false;b.textContent='Publish Vacancy';}};
}

async function renderUsers(){const el=$('admin-users');if(!el)return;const [users,purchases]=await Promise.all([read('users'),read('purchases')]);const U=Object.values(users||{}),P=Object.values(purchases||{});el.innerHTML=`<div class="admin-toolbar"><input id="user-search" placeholder="Search name or email"><select id="exam-filter"><option value="">All target exams</option>${EXAMS.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></div><div class="admin-table"><table><thead><tr><th>Aspirant</th><th>Target</th><th>Free course</th><th>Premium purchases</th><th>Registered</th><th>Last login</th></tr></thead><tbody id="users-body"></tbody></table></div>`;const draw=()=>{const q=$('user-search').value.toLowerCase().trim(),f=$('exam-filter').value;const rows=U.filter(u=>(!q||`${u.name||''} ${u.email||''}`.toLowerCase().includes(q))&&(!f||u.targetExam===f)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('users-body').innerHTML=rows.map(u=>{const ps=P.filter(p=>p.userId===u.uid);return `<tr><td><b>${esc(u.name||'—')}</b><small>${esc(u.email||'')}</small></td><td>${esc(examName(u.targetExam))}</td><td>${Object.keys(u.enrollments||{}).length?'Enrolled':'—'}</td><td>${ps.map(p=>`${esc(p.courseTitle||p.courseId)} · ${esc(p.status)}`).join('<br>')||'—'}</td><td>${formatDate(u.createdAt)}</td><td>${formatDate(u.lastLogin)}</td></tr>`}).join('')||'<tr><td colspan="6">No matching aspirants.</td></tr>';};$('user-search').oninput=draw;$('exam-filter').onchange=draw;draw();}

async function renderSimplePage(){const tests=$('admin-tests');if(tests){const raw=await read('tests');tests.innerHTML=`<div class="admin-table"><table><thead><tr><th>Test</th><th>Exam</th><th>Questions</th><th>Duration</th></tr></thead><tbody>${Object.values(raw||{}).map(t=>`<tr><td>${esc(t.title||'Untitled')}</td><td>${esc(examName(t.examId))}</td><td>${t.questions?.length||0}</td><td>${esc(t.duration||0)} min</td></tr>`).join('')||'<tr><td colspan="4">No tests published.</td></tr>'}</tbody></table></div>`;}
 const jobs=$('admin-jobs');if(jobs){const raw=await read('jobs');jobs.innerHTML=`<div class="admin-table"><table><thead><tr><th>Vacancy</th><th>Organization</th><th>Last date</th><th>Status</th></tr></thead><tbody>${Object.values(raw||{}).sort((a,b)=>(b.publishedAt||0)-(a.publishedAt||0)).map(j=>`<tr><td>${esc(j.title||'')}</td><td>${esc(j.organization||'')}</td><td>${formatDate(j.lastDate)}</td><td>${esc(j.status||'OPEN')}</td></tr>`).join('')||'<tr><td colspan="4">No vacancies published.</td></tr>'}</tbody></table></div>`;}
}
await renderBureau();await renderUsers();await renderSimplePage();
