import {onAuthStateChanged,dbGet,dbSet} from "../js/firebase.js";
import {header,footer,esc} from "../js/ui.js";
import {EXAMS} from "../js/data.js";
header();footer();
const $=id=>document.getElementById(id);
const examName=id=>EXAMS.find(e=>e.id===id)?.name||"All Exams";
const money=n=>Number(n||0)===0?"Free":"₹"+Number(n||0).toLocaleString("en-IN");
const date=v=>v?new Date(v).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
async function read(path){const s=await dbGet(path);return s.exists()?s.val():{};}
async function authAdmin(){return new Promise(resolve=>{let finished=false;onAuthStateChanged(async user=>{if(finished)return;finished=true;if(!user){location.href="../login.html?next="+encodeURIComponent(location.href);return;}try{const s=await dbGet(`admins/${user.uid}`);if(!s.exists()||s.val()!==true){document.querySelector("main").innerHTML=`<section class="section narrow"><div class="login-required"><span class="eyebrow">PRIVATE OWNER AREA</span><h1>Admin access required</h1><p>This bureau is restricted to the Firebase administrator account configured for Asha Sorkari Sakori.</p><a class="btn" href="../dashboard.html">Back to dashboard</a></div></section>`;return;}resolve(user);}catch(e){document.querySelector("main").innerHTML=`<section class="section narrow"><div class="empty">${esc(e.message)}</div></section>`;}});});}
const user=await authAdmin();if(!user)throw new Error("Admin access denied");
async function bureau(){
 const root=$("admin-root");if(!root)return;
 const [users,purchases,results,activity]=await Promise.all([read("users"),read("purchases"),read("results"),read("activity")]);
 const u=Object.values(users),p=Object.values(purchases),r=Object.values(results);
 const activities=Object.values(activity).flatMap(x=>Object.values(x||{})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));
 const approved=p.filter(x=>x.status==="approved"),pending=p.filter(x=>x.status==="pending"),revenue=approved.reduce((n,x)=>n+Number(x.amount||0),0);
 const freeEnrollments=u.reduce((n,x)=>n+Object.keys(x.enrollments||{}).length,0),courseCounts={},examCounts={};
 p.forEach(x=>courseCounts[x.courseTitle||x.courseId]=(courseCounts[x.courseTitle||x.courseId]||0)+1);u.forEach(x=>examCounts[examName(x.targetExam)]=(examCounts[examName(x.targetExam)]||0)+1);
 root.innerHTML=`<div class="stats-grid"><div class="stat-card"><small>Total aspirants</small><strong>${u.length}</strong></div><div class="stat-card"><small>Free enrollments</small><strong>${freeEnrollments}</strong></div><div class="stat-card"><small>Premium requests</small><strong>${p.length}</strong></div><div class="stat-card"><small>Pending verification</small><strong>${pending.length}</strong></div><div class="stat-card"><small>Approved revenue</small><strong>${money(revenue)}</strong></div><div class="stat-card"><small>Test submissions</small><strong>${r.length}</strong></div></div>
 <div class="bureau-nav"><a class="card" href="users.html"><b>Aspirant database</b><span>Every registered aspirant, target exam and course activity</span></a><a class="card" href="#activity"><b>Activity log</b><span>Registration, login, enrolment, payments and tests</span></a><a class="card" href="#purchases"><b>Purchase bureau</b><span>Who bought what, payment reference and access status</span></a><a class="card" href="jobs.html"><b>Vacancy management</b><span>Review published government recruitment updates</span></a></div>
 <div class="two-col"><section class="card"><span class="eyebrow">COURSE DEMAND</span><h2>Premium purchases</h2><div class="stack">${Object.entries(courseCounts).map(([k,v])=>`<div class="result-row"><div><b>${esc(k)}</b><small>purchase requests</small></div><strong>${v}</strong></div>`).join("")||`<div class="empty">No purchases yet.</div>`}</div></section><section class="card"><span class="eyebrow">ASPIRANT TARGETS</span><h2>Exam interest</h2><div class="stack">${Object.entries(examCounts).map(([k,v])=>`<div class="result-row"><div><b>${esc(k)}</b><small>registered aspirants</small></div><strong>${v}</strong></div>`).join("")||`<div class="empty">No aspirant data yet.</div>`}</div></section></div>
 <section id="purchases" class="admin-section"><div class="section-title"><div><span class="eyebrow">REVENUE & ACCESS</span><h2>Course purchase bureau</h2><p>Verify payment before granting premium access.</p></div></div><div class="admin-table-wrap"><table><thead><tr><th>Aspirant</th><th>Course</th><th>Amount</th><th>UTR / Transaction</th><th>Status</th><th>Action</th></tr></thead><tbody>${p.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(x=>`<tr><td><b>${esc(x.userName||"—")}</b><small>${esc(x.userEmail||"")}</small></td><td>${esc(x.courseTitle||x.courseId||"")}</td><td>${money(x.amount)}</td><td>${esc(x.transactionId||"—")}<small>${esc(x.paymentDate||"")}</small></td><td><span class="status ${esc(x.status||"pending")}">${esc(x.status||"pending")}</span></td><td>${x.status==="approved"?`<button class="btn tiny danger" data-revoke="${esc(x.purchaseId)}" data-user="${esc(x.userId)}" data-course="${esc(x.courseId)}">Revoke</button>`:`<button class="btn tiny" data-approve="${esc(x.purchaseId)}" data-user="${esc(x.userId)}" data-course="${esc(x.courseId)}">Approve</button>`}</td></tr>`).join("")||`<tr><td colspan="6">No premium purchase requests yet.</td></tr>`}</tbody></table></div></section>
 <section id="activity" class="admin-section"><div class="section-title"><div><span class="eyebrow">LIVE ACTIVITY RECORD</span><h2>Recent aspirant activity</h2><p>Registration, login, enrolment, payments, tests and logout events stored in Firebase.</p></div></div><div class="admin-table-wrap"><table><thead><tr><th>Time</th><th>Aspirant</th><th>Activity</th><th>Details</th></tr></thead><tbody>${activities.slice(0,100).map(a=>`<tr><td>${date(a.createdAt)}<small>${a.createdAt?new Date(a.createdAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):""}</small></td><td><b>${esc(a.email||"—")}</b></td><td>${esc(String(a.action||""))}</td><td><small>${esc(JSON.stringify(a.details||{}))}</small></td></tr>`).join("")||`<tr><td colspan="4">No activity recorded yet.</td></tr>`}</tbody></table></div></section>`;
 root.querySelectorAll("[data-approve]").forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent="Saving…";const id=b.dataset.approve,uid=b.dataset.user,cid=b.dataset.course;try{await dbSet(`purchases/${id}/status`,"approved");await dbSet(`users/${uid}/purchases/${id}/status`,"approved");await dbSet(`courseAccess/${uid}/${cid}`,true);await bureau();}catch(e){b.disabled=false;b.textContent="Approve";alert(e.message);}});
 root.querySelectorAll("[data-revoke]").forEach(b=>b.onclick=async()=>{b.disabled=true;const id=b.dataset.revoke,uid=b.dataset.user,cid=b.dataset.course;try{await dbSet(`purchases/${id}/status`,"revoked");await dbSet(`users/${uid}/purchases/${id}/status`,"revoked");await dbSet(`courseAccess/${uid}/${cid}`,false);await bureau();}catch(e){b.disabled=false;alert(e.message);}});
}
async function usersPage(){const el=$("admin-users");if(!el)return;const users=await read("users"),purchases=await read("purchases"),purchaseList=Object.values(purchases),rows=Object.values(users).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));el.innerHTML=`<div class="admin-toolbar"><input id="user-search" placeholder="Search name or email"><select id="exam-filter"><option value="">All target exams</option>${EXAMS.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join("")}</select></div><div class="admin-table-wrap"><table><thead><tr><th>Aspirant</th><th>Email</th><th>Target exam</th><th>Courses</th><th>Registered</th><th>Last login</th></tr></thead><tbody id="users-body"></tbody></table></div>`;const body=$("users-body");function draw(){const q=$("user-search").value.toLowerCase().trim(),f=$("exam-filter").value;const filtered=rows.filter(u=>(!q||`${u.name||""} ${u.email||""}`.toLowerCase().includes(q))&&(!f||u.targetExam===f));body.innerHTML=filtered.map(u=>{const ps=purchaseList.filter(p=>p.userId===u.uid),free=Object.keys(u.enrollments||{}).length;return `<tr><td><b>${esc(u.name||"—")}</b></td><td>${esc(u.email||"")}</td><td>${esc(examName(u.targetExam))}</td><td><small>Free: ${free} · Premium: ${ps.length}</small><br>${ps.slice(0,3).map(p=>esc(p.courseTitle)+` (${esc(p.status)})`).join("<br>")||"—"}</td><td>${date(u.createdAt)}</td><td>${u.lastLogin?date(u.lastLogin):"—"}</td></tr>`}).join("")||`<tr><td colspan="6">No matching aspirants.</td></tr>`;}draw();$("user-search").oninput=draw;$("exam-filter").onchange=draw;}
async function testsPage(){const el=$("admin-tests");if(!el)return;const t=await read("tests");el.innerHTML=`<table><thead><tr><th>Test</th><th>Exam</th><th>Questions</th><th>Duration</th></tr></thead><tbody>${Object.values(t).map(x=>`<tr><td>${esc(x.title||"Untitled")}</td><td>${esc(examName(x.examId))}</td><td>${x.questions?.length||0}</td><td>${x.duration||0} min</td></tr>`).join("")||`<tr><td colspan="4">No Firebase tests published yet.</td></tr>`}</tbody></table>`;}
async function jobsPage(){const el=$("admin-jobs");if(!el)return;const j=await read("jobs");el.innerHTML=`<table><thead><tr><th>Vacancy</th><th>Organization</th><th>Last date</th><th>Status</th></tr></thead><tbody>${Object.values(j).sort((a,b)=>(b.publishedAt||0)-(a.publishedAt||0)).map(x=>`<tr><td>${esc(x.title||"")}</td><td>${esc(x.organization||"")}</td><td>${date(x.lastDate)}</td><td>${esc(x.status||"—")}</td></tr>`).join("")||`<tr><td colspan="4">No vacancies published yet.</td></tr>`}</tbody></table>`;}
await bureau();await usersPage();await testsPage();await jobsPage();
